# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-13 01:24
from __future__ import unicode_literals

from django.db import migrations, models
import helpers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('interface', models.CharField(max_length=10)),
                ('ip_range', helpers.models.CIDRNetworkField()),
                ('policy', models.CharField(choices=[('reject', 'Reject'), ('drop', 'Ignore'), ('accept', 'Accept')], max_length=6, verbose_name='default policy')),
            ],
        ),
    ]
